services:
    backend:
        build: .
        container_name: point-reward-backend
        restart: always
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=development
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/redeem_points
            - JWT_SECRET=supersecretkey
        depends_on:
            - mongo

    mongo:
        image: mongo:5.0
        container_name: mongo
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - '8081:8081'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
    mongo-data:
