services:
    backend:
        build: .
        container_name: point-reward-backend
        restart: always
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=production
            - PORT=5000
            - MONGO_URI=${MONGO_URI}
            - JWT_SECRET=${JWT_SECRET}
        volumes:
            - .:/app
        depends_on:
            - mongo-express

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - '8081:8081'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
